# Generated by Django 5.1.4 on 2025-01-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_category_ingredient_product_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(blank=True, null=True, upload_to='user/product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to='user/product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, null=True, upload_to='user/product_pic/'),
        ),
    ]
