# Generated by Django 5.1.4 on 2025-01-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
