# Generated by Django 5.1.4 on 2025-01-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
