# Generated by Django 5.1.4 on 2025-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_remove_product_ingredients_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(upload_to='user/product_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(default='user/product_pic/1-dryfruit-banner.jpg', upload_to='user/product_pic/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(default=2, upload_to='user/product_pic/'),
            preserve_default=False,
        ),
    ]
