# Generated by Django 5.1.4 on 2025-01-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_address_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
