# Generated by Django 5.1.4 on 2025-01-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_remove_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
