# Generated by Django 5.1.4 on 2025-01-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_remove_orderitem_product_orderitem_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
