# Generated by Django 5.1.4 on 2025-01-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_razorpay_remove_transaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
