# Generated by Django 5.1.4 on 2025-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
