# Generated by Django 5.1.4 on 2025-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_order_discout_percentage_orderitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='Default Name', max_length=50),
            preserve_default=False,
        ),
    ]
