# Generated by Django 5.1.4 on 2025-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_orderitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
