# Generated by Django 5.1.4 on 2025-02-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_remove_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_price',
        ),
    ]
