# Generated by Django 5.1.4 on 2025-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_remove_orderitem_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_price_per_order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
